//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Taxonomy_Change_Management_Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HR_Taxonomy_Change_Management_Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;ChangePeriodId&quot;: 1,
        ///    &quot;StartDate&quot;: &quot;2023-10-06T00:00:00&quot;,
        ///    &quot;EndDate&quot;: &quot;2023-12-23T00:00:00&quot;,
        ///    &quot;CreateUser&quot;: &quot;v-reedchris@microsoft.com&quot;,
        ///    &quot;CreateDate&quot;: &quot;2023-10-03T00:00:00&quot;,
        ///    &quot;ModifyUser&quot;: &quot;v-reedchris@microsoft.com&quot;,
        ///    &quot;ModifyDate&quot;: &quot;2023-12-19T19:13:13.7342018&quot;,
        ///    &quot;IsDeleted&quot;: false,
        ///    &quot;IsClosed&quot;: false,
        ///    &quot;Requests&quot;: null
        ///  },
        ///  {
        ///    &quot;ChangePeriodId&quot;: 2,
        ///    &quot;StartDate&quot;: &quot;1900-01-01T00:00:00&quot;,
        ///    &quot;EndDate&quot;: &quot;2023-01-01T00:00:00&quot;,
        ///    &quot;CreateUser&quot;: &quot;v-r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChangePeriodJson {
            get {
                return ResourceManager.GetString("ChangePeriodJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;ChangeStatusTypeId&quot;: 1,
        ///    &quot;StatusTypeName&quot;: &quot;New&quot;
        ///  },
        ///  {
        ///    &quot;ChangeStatusTypeId&quot;: 2,
        ///    &quot;StatusTypeName&quot;: &quot;Pending Review&quot;
        ///  },
        ///  {
        ///    &quot;ChangeStatusTypeId&quot;: 3,
        ///    &quot;StatusTypeName&quot;: &quot;Denied&quot;
        ///  },
        ///  {
        ///    &quot;ChangeStatusTypeId&quot;: 4,
        ///    &quot;StatusTypeName&quot;: &quot;Approved&quot;
        ///  }
        ///].
        /// </summary>
        internal static string ChangeStatusTypeJson {
            get {
                return ResourceManager.GetString("ChangeStatusTypeJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;RequestId&quot;: 1486,
        ///    &quot;Justification&quot;: &quot;lllllllllllllllllllllllllllllllllllllllllllllllllllllll&quot;,
        ///    &quot;Change&quot;: &quot;&lt;ul&gt;&lt;li&gt;Governance, Risk Management, Controls and Compliance (GRCC) &gt; Business Continuity &gt; Business Continuity Plan Development &gt; &lt;span style=\&quot;color:#e50000; \&quot;&gt;Plan Documentation is removed &lt;/span&gt;&lt;/li&gt;&lt;li&gt;Governance, Risk Management, Controls and Compliance (GRCC) &gt; Business Continuity &gt; Business Continuity Plan Development &gt; &lt;span style=\&quot;color:#e50000; \&quot;&gt;Procedure Developmen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestJsonData {
            get {
                return ResourceManager.GetString("RequestJsonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;RequestStatusTypeId&quot;: 1,
        ///    &quot;StatusTypeName&quot;: &quot;Open&quot;
        ///  },
        ///  {
        ///    &quot;RequestStatusTypeId&quot;: 2,
        ///    &quot;StatusTypeName&quot;: &quot;Closed&quot;
        ///  }
        ///].
        /// </summary>
        internal static string RequestStatusTypeJson {
            get {
                return ResourceManager.GetString("RequestStatusTypeJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;RequestTypeId&quot;: 1,
        ///    &quot;RequestTypeName&quot;: &quot;New&quot;
        ///  },
        ///  {
        ///    &quot;RequestTypeId&quot;: 2,
        ///    &quot;RequestTypeName&quot;: &quot;Move&quot;
        ///  },
        ///  {
        ///    &quot;RequestTypeId&quot;: 3,
        ///    &quot;RequestTypeName&quot;: &quot;Rename&quot;
        ///  },
        ///  {
        ///    &quot;RequestTypeId&quot;: 4,
        ///    &quot;RequestTypeName&quot;: &quot;Remove&quot;
        ///  }
        ///].
        /// </summary>
        internal static string RequestTypeJsonData {
            get {
                return ResourceManager.GetString("RequestTypeJsonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;TaxonomyId&quot;: 1,
        ///    &quot;Name&quot;: &quot;Benefits&quot;,
        ///    &quot;ParentId&quot;: null,
        ///    &quot;ParentTaxonomy&quot;: null,
        ///    &quot;ChildTaxonomy&quot;: [
        ///      {
        ///        &quot;TaxonomyId&quot;: 12,
        ///        &quot;Name&quot;: &quot;Benefits Management&quot;,
        ///        &quot;ParentId&quot;: 1,
        ///        &quot;ChildTaxonomy&quot;: [
        ///          {
        ///            &quot;TaxonomyId&quot;: 88,
        ///            &quot;Name&quot;: &quot;Benefits Enrollment Administration&quot;,
        ///            &quot;ParentId&quot;: 12,
        ///            &quot;ChildTaxonomy&quot;: [
        ///              {
        ///                &quot;TaxonomyId&quot;: 396,
        ///                &quot;Name&quot;: &quot;Disenrollme [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TaxonomyJson {
            get {
                return ResourceManager.GetString("TaxonomyJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;OwnerId&quot;: 1,
        ///    &quot;OwnerName&quot;: &quot;Majo Alatriste Parrodi&quot;,
        ///    &quot;OwnerEmail&quot;: &quot;maalatri@microsoft.com&quot;,
        ///    &quot;Taxonomies&quot;: null
        ///  },
        ///  {
        ///    &quot;OwnerId&quot;: 2,
        ///    &quot;OwnerName&quot;: &quot;Pam Dara&quot;,
        ///    &quot;OwnerEmail&quot;: &quot;gooltz@microsoft.com&quot;,
        ///    &quot;Taxonomies&quot;: null
        ///  },
        ///  {
        ///    &quot;OwnerId&quot;: 3,
        ///    &quot;OwnerName&quot;: &quot;Patti Yanez&quot;,
        ///    &quot;OwnerEmail&quot;: &quot;pyanez@microsoft.com&quot;,
        ///    &quot;Taxonomies&quot;: null
        ///  },
        ///  {
        ///    &quot;OwnerId&quot;: 4,
        ///    &quot;OwnerName&quot;: &quot;Dawn Chase&quot;,
        ///    &quot;OwnerEmail&quot;: &quot;dawncha@microsoft.com&quot;,
        ///    &quot;Taxo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TaxonomyOwnerJson {
            get {
                return ResourceManager.GetString("TaxonomyOwnerJson", resourceCulture);
            }
        }
    }
}
